/* $Log:        typedef.h $
 * Revision 1.4  92/08/17  16:43:02  crm
 * Automatic checkin
 *
 * Revision 1.3  92/08/17  15:23:46  Unknown
 * releasing locks
 *
 * Revision 1.2  92/08/17  15:08:29  Unknown
 * Added log entries and RCS bookkeeping
 *
 * Revision 1.1  92/08/17  14:53:01  Unknown
 * Initial revision
 *  */
/* deftype.h -- some deftypes
 *
 *
 */
/* Type definitions */
#ifndef TYPEDEF
#define TYPEDEF

typedef unsigned char   uchar;
typedef unsigned short  ushort;
typedef unsigned long   ulong;

typedef uchar far * LPBUF;
typedef uchar far * LPFUN;
typedef uchar far * LPSZ;
#endif
